import { largeImages } from "../data/largeImages";

const RASTER = /\.(png|jpe?g)$/i;

/** Small WebP copy for cards/tiles (generated by scripts/optimize-images.py). */
export function thumb(src: string) {
  return RASTER.test(src) ? `thumbs/${src.replace(RASTER, ".webp")}` : src;
}

/** Lightbox source: a 2560px WebP for very large originals, otherwise the original. */
export function full(src: string) {
  return largeImages.has(src) ? `large/${src.replace(RASTER, ".webp")}` : src;
}
