"""Generate web-sized copies of portfolio images (originals are never modified).

  public/thumbs/<path>.webp  - max 960px, used by grid cards and tiles
  public/large/<path>.webp   - max 2560px, only for originals over 5 MB; used by the lightbox

Also writes src/data/largeImages.ts listing which originals have a large copy.
Re-run after adding images:  python scripts/optimize-images.py   (needs Pillow)
"""

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
PUBLIC = ROOT / "public"
SOURCES = ["images", "certificates"]
EXTS = {".png", ".jpg", ".jpeg"}
THUMB_MAX = 960
LARGE_MAX = 2560
LARGE_THRESHOLD = 5 * 1024 * 1024

Image.MAX_IMAGE_PIXELS = None  # the big composites exceed Pillow's default guard


def save_resized(src: Path, dest: Path, max_side: int, quality: int) -> None:
    if dest.exists() and dest.stat().st_mtime >= src.stat().st_mtime:
        return
    dest.parent.mkdir(parents=True, exist_ok=True)
    with Image.open(src) as im:
        im.thumbnail((max_side, max_side), Image.LANCZOS)
        if im.mode not in ("RGB", "RGBA"):
            im = im.convert("RGBA")
        im.save(dest, "WEBP", quality=quality, method=6)
    print(f"  {dest.relative_to(PUBLIC)}")


def main() -> None:
    large = []
    for folder in SOURCES:
        for src in sorted((PUBLIC / folder).rglob("*")):
            if src.suffix.lower() not in EXTS:
                continue
            rel = src.relative_to(PUBLIC).with_suffix(".webp")
            save_resized(src, PUBLIC / "thumbs" / rel, THUMB_MAX, 80)
            if src.stat().st_size > LARGE_THRESHOLD:
                save_resized(src, PUBLIC / "large" / rel, LARGE_MAX, 86)
                large.append(src.relative_to(PUBLIC).as_posix())

    lines = ",\n".join(f'  "{p}"' for p in large)
    (ROOT / "src" / "data" / "largeImages.ts").write_text(
        "// Generated by scripts/optimize-images.py - originals that have a public/large/ copy.\n"
        f"export const largeImages = new Set<string>([\n{lines},\n]);\n",
        encoding="utf-8",
    )
    print(f"done ({len(large)} large copies)")


if __name__ == "__main__":
    main()
